<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UsersSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'superadm.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Super Admin User',
                'mname'          => 'James',
                'lname'          => 'Anderson',
                'fullname'       => 'Super Admin User James Anderson',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 1,
                'federation_id'  => null,
                'local_union_id' => null,
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'adm.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Admin User',
                'mname'          => 'Marie',
                'lname'          => 'Brown',
                'fullname'       => 'Admin User Marie Brown',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 2,
                'federation_id'  => null,
                'local_union_id' => null,
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'federation1.user1@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Ethan',
                'mname'          => 'Fedor',
                'lname'          => 'Johnson',
                'fullname'       => 'Ethan Fedor Johnson',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 3,
                'federation_id'  => '1',
                'local_union_id' => null,
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'federation1.user2@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Maya',
                'mname'          => 'Federica',
                'lname'          => 'Clark',
                'fullname'       => 'Maya Federica Clark',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 3,
                'federation_id'  => '1',
                'local_union_id' => null,
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'federation14.user1@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Lucas',
                'mname'          => 'Fedor',
                'lname'          => 'Morris',
                'fullname'       => 'Lucas Fedor Morris',
                'photo'          => '1',
                'status_id'      => '0',
                'role_id'        => 3,
                'federation_id'  => '14',
                'local_union_id' => null,
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'federation14.user2@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Isabella',
                'mname'          => 'Sylvia',
                'lname'          => 'Walker',
                'fullname'       => 'Isabella Sylvia Walker',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 3,
                'federation_id'  => '14',
                'local_union_id' => null,
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union1.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Oliver',
                'mname'          => 'Jonathan',
                'lname'          => 'King',
                'fullname'       => 'Oliver Jonathan King',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '1',
                'local_union_id' => '1',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union2.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Emma',
                'mname'          => 'Joanne',
                'lname'          => 'Scott',
                'fullname'       => 'Emma Joanne Scott',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '1',
                'local_union_id' => '2',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union3.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Noah',
                'mname'          => 'Jacob',
                'lname'          => 'Green',
                'fullname'       => 'Noah Jacob Green',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '14',
                'local_union_id' => '3',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union4.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Sophia',
                'mname'          => 'Grace',
                'lname'          => 'Adams',
                'fullname'       => 'Sophia Grace Adams',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '14',
                'local_union_id' => '4',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union5.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Liam',
                'mname'          => 'Edward',
                'lname'          => 'Carter',
                'fullname'       => 'Liam Edward Carter',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '1',
                'local_union_id' => '1',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union6.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Mia',
                'mname'          => 'Elizabeth',
                'lname'          => 'James',
                'fullname'       => 'Mia Elizabeth James',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '1',
                'local_union_id' => '2',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union7.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Elijah',
                'mname'          => 'Michael',
                'lname'          => 'Baker',
                'fullname'       => 'Elijah Michael Baker',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '14',
                'local_union_id' => '3',
            ],
            [
                'guid'           => (string) Str::uuid(),
                'email'          => 'union8.user@mailinator.com',
                'password'       => Hash::make('S@mple123'),
                'fname'          => 'Charlotte',
                'mname'          => 'Anne',
                'lname'          => 'Nelson',
                'fullname'       => 'Charlotte Anne Nelson',
                'photo'          => '1',
                'status_id'      => '1',
                'role_id'        => 4,
                'federation_id'  => '14',
                'local_union_id' => '4',
            ],
        ]);
    }
}
